package com.acme.migration.vmmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VMInstance implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public VMInstance() {
    }

}