package com.acme.migration.vmmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VMInstance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "vm instance identifier")
   private java.lang.Integer vminstanceId;
   @org.kie.api.definition.type.Label(value = "name of vm")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "date of creation")
   private java.util.Date createddate;
   @org.kie.api.definition.type.Label(value = "host identifier")
   private java.lang.Integer hostid;
   @org.kie.api.definition.type.Label(value = "number of cores")
   private java.lang.Integer numberofCores;
   @org.kie.api.definition.type.Label(value = "memory of VM")
   private java.lang.Integer memory;
   @org.kie.api.definition.type.Label(value = "operating system type")
   private java.lang.String ostype;
   @org.kie.api.definition.type.Label(value = "status")
   private java.lang.Boolean isActive;
   @org.kie.api.definition.type.Label(value = "running status")
   private java.lang.Boolean isRunning;

   public VMInstance()
   {
   }

   public java.lang.Integer getVminstanceId()
   {
      return this.vminstanceId;
   }

   public void setVminstanceId(java.lang.Integer vminstanceId)
   {
      this.vminstanceId = vminstanceId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.Date getCreateddate()
   {
      return this.createddate;
   }

   public void setCreateddate(java.util.Date createddate)
   {
      this.createddate = createddate;
   }

   public java.lang.Integer getHostid()
   {
      return this.hostid;
   }

   public void setHostid(java.lang.Integer hostid)
   {
      this.hostid = hostid;
   }

   public java.lang.Integer getNumberofCores()
   {
      return this.numberofCores;
   }

   public void setNumberofCores(java.lang.Integer numberofCores)
   {
      this.numberofCores = numberofCores;
   }

   public java.lang.Integer getMemory()
   {
      return this.memory;
   }

   public void setMemory(java.lang.Integer memory)
   {
      this.memory = memory;
   }

   public java.lang.String getOstype()
   {
      return this.ostype;
   }

   public void setOstype(java.lang.String ostype)
   {
      this.ostype = ostype;
   }

   public java.lang.Boolean getIsActive()
   {
      return this.isActive;
   }

   public void setIsActive(java.lang.Boolean isActive)
   {
      this.isActive = isActive;
   }

   public java.lang.Boolean getIsRunning()
   {
      return this.isRunning;
   }

   public void setIsRunning(java.lang.Boolean isRunning)
   {
      this.isRunning = isRunning;
   }

   public VMInstance(java.lang.Integer vminstanceId, java.lang.String name,
         java.util.Date createddate, java.lang.Integer hostid,
         java.lang.Integer numberofCores, java.lang.Integer memory,
         java.lang.String ostype, java.lang.Boolean isActive,
         java.lang.Boolean isRunning)
   {
      this.vminstanceId = vminstanceId;
      this.name = name;
      this.createddate = createddate;
      this.hostid = hostid;
      this.numberofCores = numberofCores;
      this.memory = memory;
      this.ostype = ostype;
      this.isActive = isActive;
      this.isRunning = isRunning;
   }

}